# 读取数据

In [273]:
import pandas as pd

In [274]:
df_raw = pd.read_csv("fsnd_zb_data.tsv",encoding="utf8",sep="\t", \
                        keep_default_na=False,na_values="na_rep",index_col=[0,1,2])
df_m = pd.read_csv ("fsnd_zb_meta1.tsv",encoding="utf8",sep="\t",keep_default_na=False,na_values="na_rep",index_col=[0])
df_r = pd.read_csv ("reg_treeId_level2.tsv",encoding="utf8",sep="\t",keep_default_na=False,na_values="na_rep")
display(df_r.tail())
# df_jy = pd.read_csv ("就业切片.tsv", encoding = "utf-8", sep ="\t")

      i dbcode exp      id  isParent      name   open     pid   wd
128   7   fsnd      610000      True       陕西省  False  900003  reg
129   8   fsnd      620000      True       甘肃省  False  900003  reg
130   9   fsnd      630000      True       青海省  False  900003  reg
131  10   fsnd      640000      True   宁夏回族自治区  False  900003  reg
132  11   fsnd      650000      True  新疆维吾尔自治区  False  900003  reg

In [275]:
df_raw.shape

(908300, 1)

In [276]:
df_m

,cname,dotcount,exp,ifshowcode,memo,name,nodesort,sortcode,tag,unit
code,,,,,,,,,,
A010101,地级区划数,0,指地级行政单位即介于省级和县级之间的一级地方行政区域的个数，包括地区、自治州、行政区和盟。,False,,地级区划数,1,2,,个
A010102,地级市数,0,市是省、自治区内人口较集中，政治、经济、文化等方面较重要的城市。市人民政府为一级地方行政组织...,False,,地级市数,1,3,,个
A010103,县级区划数,0,县级行政单位指中国地方二级行政区域，是地方政权的基础。县级行政单位包括县、自治县、旗、自治旗...,False,,县级区划数,1,4,,个
A010104,市辖区数,0,市辖区（简称区）城市基层政权组织的行政区域。直辖市和较大的市多将市区范围划分为若干区，设立区...,False,,市辖区数,1,5,,个
A010105,县级市数,0,县级市是中国大陆行政区划名称，行政地位与县相同的县级行政区,False,,县级市数,1,6,,个
...,...,...,...,...,...,...,...,...,...,...
A0S0B01,城乡居民社会养老保险参保人数,1,,False,,城乡居民社会养老保险参保人数,1,3355,,万人
A0S0B02,城乡居民社会养老保险实际领取待遇人数,1,,False,,城乡居民社会养老保险实际领取待遇人数,1,3356,,万人
A0S0B03,城乡居民社会养老保险基金收入,1,,False,,城乡居民社会养老保险基金收入,1,3357,,亿元
A0S0B04,城乡居民社会养老保险基金支出,1,,False,,城乡居民社会养老保险基金支出,1,3358,,亿元
A0S0B05,城乡居民社会养老保险累计结余,1,,False,,城乡居民社会养老保险累计结余,1,3359,,亿元

## 创建相关字典

In [277]:
# 创建指标字典
指标字典 = df_m['cname'].to_dict()
指标字典

{'A010101': '地级区划数',
 'A010102': '地级市数',
 'A010103': '县级区划数',
 'A010104': '市辖区数',
 'A010105': '县级市数',
 'A010106': '县数',
 'A010107': '自治县数',
 'A010108': '乡镇级区划数',
 'A010109': '镇数',
 'A01010A': '乡数',
 'A01010B': '街道办事处',
 'A010201': '三次产业法人单位数',
 'A010202': '分机构类型法人单位数',
 'A010203': '分行业法人单位数',
 'A010301': '按控股情况分企业法人单位数',
 'A010302': '按登记注册类型分企业法人单位数',
 'A020101': '地区生产总值',
 'A020102': '第一产业增加值',
 'A020103': '第二产业增加值',
 'A020104': '第三产业增加值',
 'A020105': '农林牧渔业增加值',
 'A020106': '工业增加值',
 'A020107': '建筑业增加值',
 'A020108': '批发和零售业增加值',
 'A020109': '批发和零售贸易餐饮业增加值',
 'A02010A': '交通运输、仓储和邮政业增加值',
 'A02010B': '交通运输、仓储和邮电通信业增加值',
 'A02010C': '住宿和餐饮业增加值',
 'A02010D': '金融业增加值',
 'A02010E': '房地产业增加值',
 'A02010F': '其他行业增加值',
 'A02010G': '人均地区生产总值',
 'A020201': '地区生产总值指数(上年=100)',
 'A020202': '第一产业增加值指数(上年=100)',
 'A020203': '第二产业增加值指数(上年=100)',
 'A020204': '第三产业增加值指数(上年=100)',
 'A020301': '收入法生产总值',
 'A020302': '劳动者报酬',
 'A020303': '生产税净额',
 'A020304': '固定资产折旧',
 'A020305': '营业盈余',
 'A020401': '支出法生产总值',
 'A020402': '最终消费',
 'A020403': '居民消费',
 'A020404': '农村居民消费',
 'A020405': '城镇居民消费',
 'A020406': '政府消费',
 'A020407': '资本形成总额',
 'A020408': '固定资本形成总额',
 'A020409': '存货增加',
 'A02040A': '货物和服务净流出',
 'A02040B': '最终消费率',
 'A02040C': '资本形成率',
 'A020501': '居民消费水平',
 'A020502': '农村居民消费水平',
 'A020503': '城镇居民消费水平',
 'A020504': '居民消费水平指数(上年=100)',
 'A020505': '农村居民消费水平指数(上年=100)',
 'A020506': '城镇居民消费水平指数(上年=100)',
 'A030101': '年末常住人口',
 'A030102': '城镇人口',
 'A030103': '乡村人口',
 'A030201': '人口出生率',
 'A030202': '人口死亡率',
 'A030203': '人口自然增长率',
 'A030301': '平均预期寿命',
 'A030302': '男性平均预期寿命',
 'A030303': '女性平均预期寿命',
 'A030801': '人口数(人口抽样调查)',
 'A030802': '户数、户人口及户规模(人口抽样调查)',
 'A030803': '按户口登记状况分人口数(人口抽样调查)',
 'A030804': '人口年龄构成和抚养比(人口抽样调查)',
 'A030805': '按婚姻状况分人口数(人口抽样调查)',
 'A030806': '按受教育程度分人口数(人口抽样调查)',
 'A030807': '15岁及以上文盲人口(人口抽样调查)',
 'A030808': '按家庭户规模分的户数(人口抽样调查)',
 'A040101': '城镇单位就业人员',
 'A040102': '农林牧渔业城镇单位就业人员',
 'A040103': '采矿业城镇单位就业人员',
 'A040104': '制造业城镇单位就业人员',
 'A040105': '电力、燃气及水的生产和供应业城镇单位就业人员',
 'A040106': '建筑业城镇单位就业人员',
 'A040107': '交通运输、仓储及邮电通信业城镇单位就业人员',
 'A040108': '信息传输、计算机服务和软件业城镇单位就业人员',
 'A040109': '批发和零售业城镇单位就业人员',
 'A04010A': '住宿和餐饮业城镇单位就业人员',
 'A04010B': '金融业城镇单位就业人员',
 'A04010C': '房地产业城镇单位就业人员',
 'A04010D': '租赁和商务服务业城镇单位就业人员',
 'A04010E': '科学研究、技术服务和地质勘查业城镇单位就业人员',
 'A04010F': '水利、环境和公共设施管理业城镇单位就业人员',
 'A04010G': '居民服务和其他服务业城镇单位就业人员',
 'A04010H': '教育业城镇单位就业人员',
 'A04010I': '卫生、社会保障和社会福利业城镇单位就业人员',
 'A04010J': '文化、体育和娱乐业城镇单位就业人员',
 'A04010K': '公共管理和社会组织城镇单位就业人员',
 'A040201': '私营企业和个体就业人员',
 'A040202': '制造业私营企业和个体就业人员',
 'A040203': '建筑业私营企业和个体就业人员',
 'A040204': '交通运输、仓储和邮政业私营企业和个体就业人员',
 'A040205': '批发和零售业私营企业和个体就业人员',
 'A040206': '住宿和餐饮业私营企业和个体就业人员',
 'A040207': '租赁和商务服务业私营企业和个体就业人员',
 'A040208': '居民服务和其他服务业私营企业和个体就业人员',
 'A040301': '城镇私营企业和个体就业人员',
 'A040302': '制造业城镇私营企业和个体就业人员',
 'A040303': '建筑业城镇私营企业和个体就业人员',
 'A040304': '交通运输、仓储和邮政业城镇私营企业和个体就业人员',
 'A040305': '批发和零售业城镇私营企业和个体就业人员',
 'A040306': '住宿和餐饮业城镇私营企业和个体就业人员',
 'A040307': '租赁和商务服务业城镇私营企业和个体就业人员',
 'A040308': '居民服务和其他服务业城镇私营企业和个体就业人员',
 'A040401': '私营企业户数',
 'A040402': '私营企业就业人数',
 'A040403': '私营企业投资者就业人数',
 'A040404': '城镇私营企业就业人数',
 'A040405': '城镇私营企业投资者就业人数',
 'A040406': '乡村私营企业就业人数',
 'A040407': '乡村私营企业投资者就业人数',
 'A040501': '个体户数',
 'A040502': '个体就业人数',
 'A040503': '城镇就业人数',
 'A040504': '乡村个体就业人数',
 'A040601': '城镇单位就业人员工资总额',
 'A040602': '国有城镇单位就业人员工资总额',
 'A040603': '城镇集体单位就业人员工资总额',
 'A040604': '其他城镇单位就业人员工资总额',
 'A040605': '城镇单位就业人员工资总额指数(上年=100)',
 'A040606': '国有城镇单位就业人员工资总额指数(上年=100)',
 'A040607': '城镇集体单位就业人员工资总额指数(上年=100)',
 'A040608': '其他城镇单位就业人员工资总额指数(上年=100)',
 'A040701': '城镇单位就业人员平均工资',
 'A040702': '城镇单位在岗职工平均工资',
 'A040703': '城镇国有单位就业人员平均工资',
 'A040704': '城镇集体单位就业人员平均工资',
 'A040705': '城镇其他单位就业人员平均工资',
 'A040706': '城镇单位就业人员平均货币工资指数(上年=100)',
 'A040707': '城镇单位在岗职工平均货币工资指数(上年=100)',
 'A040708': '国有城镇单位就业人员平均货币工资指数(上年=100)',
 'A040709': '城镇集体单位就业人员平均货币工资指数(上年=100)',
 'A04070A': '其他城镇单位就业人员平均货币工资指数(上年=100)',
 'A04070B': '城镇单位就业人员平均实际工资指数(上年=100)',
 'A04070C': '城镇单位在岗职工平均实际工资指数(上年=100)',
 'A04070D': '国有城镇单位就业人员平均实际工资指数(上年=100)',
 'A04070E': '城镇集体单位就业人员平均实际工资指数(上年=100)',
 'A04070F': '其他城镇单位就业人员平均实际工资指数(上年=100)',
 'A040801': '城镇单位就业人员平均工资',
 'A040802': '国有单位就业人员平均工资',
 'A040803': '城镇集体单位就业人员平均工资',
 'A040804': '股份合作单位就业人员平均工资',
 'A040805': '联营单位就业人员平均工资',
 'A040806': '有限责任公司就业人员平均工资',
 'A040807': '股份有限公司就业人员平均工资',
 'A040808': '其他单位就业人员平均工资',
 'A040809': '港、澳、台商投资单位就业人员平均工资',
 'A04080A': '外商投资单位就业人员平均工资',
 'A040901': '城镇单位就业人员工资总额',
 'A040902': '农、林、牧、渔业城镇单位就业人员工资总额',
 'A040903': '采矿业城镇单位就业人员工资总额',
 'A040904': '制造业城镇单位就业人员工资总额',
 'A040905': '电力、燃气及水的生产和供应业城镇单位就业人员工资总额',
 'A040906': '建筑业城镇单位就业人员工资总额',
 'A040907': '交通运输、仓储和邮政业城镇单位就业人员工资总额',
 'A040908': '信息传输、计算机服务和软件业城镇单位就业人员工资总额',
 'A040909': '批发和零售业城镇单位就业人员工资总额',
 'A04090A': '住宿和餐饮业城镇单位就业人员工资总额',
 'A04090B': '金融业城镇单位就业人员工资总额',
 'A04090C': '房地产业城镇单位就业人员工资总额',
 'A04090D': '租赁和商务服务业城镇单位就业人员工资总额',
 'A04090E': '科学研究、技术服务和地质勘查业城镇单位就业人员工资总额',
 'A04090F': '水利、环境和公共设施管理业城镇单位就业人员工资总额',
 'A04090G': '居民服务和其他服务业城镇单位就业人员工资总额',
 'A04090H': '教育城镇单位就业人员工资总额',
 'A04090I': '卫生、社会保障和社会福利业城镇单位就业人员工资总额',
 'A04090J': '文化、体育和娱乐业城镇单位就业人员工资总额',
 'A04090K': '公共管理和社会组织城镇单位就业人员工资总额',
 'A040A01': '城镇单位就业人员平均工资',
 'A040A02': '农、林、牧、渔业城镇单位就业人员平均工资',
 'A040A03': '采矿业城镇单位就业人员平均工资',
 'A040A04': '制造业城镇单位就业人员平均工资',
 'A040A05': '电力、燃气及水的生产和供应业城镇单位就业人员平均工资',
 'A040A06': '建筑业城镇单位就业人员平均工资',
 'A040A07': '交通运输、仓储和邮政业城镇单位就业人员平均工资',
 'A040A08': '信息传输、计算机服务和软件业城镇单位就业人员平均工资',
 'A040A09': '批发和零售业城镇单位就业人员平均工资',
 'A040A0A': '住宿和餐饮业城镇单位就业人员平均工资',
 'A040A0B': '金融业城镇单位就业人员平均工资',
 'A040A0C': '房地产业城镇单位就业人员平均工资',
 'A040A0D': '租赁和商务服务业城镇单位就业人员平均工资',
 'A040A0E': '科学研究、技术服务和地质勘查业城镇单位就业人员平均工资',
 'A040A0F': '水利、环境和公共设施管理业城镇单位就业人员平均工资',
 'A040A0G': '居民服务和其他服务业城镇单位就业人员平均工资',
 'A040A0H': '教育城镇单位就业人员平均工资',
 'A040A0I': '卫生、社会保障和社会福利业城镇单位就业人员平均工资',
 'A040A0J': '文化、体育和娱乐业城镇单位就业人员平均工资',
 'A040A0K': '公共管理和社会组织城镇单位就业人员平均工资',
 'A040B01': '城镇私营单位就业人员平均工资',
 'A040B02': '农、林、牧、渔业城镇私营单位就业人员平均工资',
 'A040B03': '采矿业城镇私营单位就业人员平均工资',
 'A040B04': '制造业城镇私营单位就业人员平均工资',
 'A040B05': '电力、燃气及水的生产和供应业城镇私营单位就业人员平均工资',
 'A040B06': '建筑业城镇私营单位就业人员平均工资',
 'A040B07': '交通运输、仓储和邮政业城镇私营单位就业人员平均工资',
 'A040B08': '信息传输、计算机服务和软件业城镇私营单位就业人员平均工资',
 'A040B09': '批发和零售业城镇私营单位就业人员平均工资',
 'A040B0A': '住宿和餐饮业城镇私营单位就业人员平均工资',
 'A040B0B': '金融业城镇私营单位就业人员平均工资',
 'A040B0C': '房地产业城镇私营单位就业人员平均工资',
 'A040B0D': '租赁和商务服务业城镇私营单位就业人员平均工资',
 'A040B0E': '科学研究、技术服务和地质勘查业城镇私营单位就业人员平均工资',
 'A040B0F': '水利、环境和公共设施管理业城镇私营单位就业人员平均工资',
 'A040B0G': '居民服务和其他服务业城镇私营单位就业人员平均工资',
 'A040B0H': '教育城镇私营单位就业人员平均工资',
 'A040B0I': '卫生、社会保障和社会福利业城镇私营单位就业人员平均工资',
 'A040B0J': '文化、体育和娱乐业城镇私营单位就业人员平均工资',
 'A040B0K': '公共管理和社会组织城镇私营单位就业人员平均工资',
 'A040C01': '城镇登记失业人数',
 'A040C02': '城镇登记失业率',
 'A050101': '全社会固定资产投资',
 'A050102': '城镇固定资产投资',
 'A050103': '房地产开发投资',
 'A050201': '全社会固定资产投资',
 'A050202': '内资企业全社会固定资产投资',
 'A050203': '国有全社会固定资产投资',
 'A050204': '集体全社会固定资产投资',
 'A050205': '股份合作全社会固定资产投资',
 'A050206': '联营全社会固定资产投资',
 'A050207': '有限责任公司全社会固定资产投资',
 'A050208': '股份有限公司全社会固定资产投资',
 'A050209': '私营全社会固定资产投资',
 'A05020A': '个体全社会固定资产投资',
 'A05020B': '其他全社会固定资产投资',
 'A05020C': '港、澳、台商投资全社会固定资产投资',
 'A05020D': '外商投资全社会固定资产投资',
 'A050301': '全社会固定资产本年资金来源小计',
 'A050302': '全社会固定资产投资中国家预算内资金',
 'A050303': '全社会固定资产投资中国内贷款',
 'A050304': '全社会固定资产投资中利用外资',
 'A050305': '全社会固定资产投资中自筹资金',
 'A050306': '全社会固定资产投资中其他资金',
 'A050401': '全社会住宅投资',
 'A050402': '城镇住宅投资',
 'A050403': '房地产住宅投资',
 'A050501': '全社会固定资产投资',
 'A050502': '农、林、牧、渔业全社会固定资产投资',
 'A050503': '采矿业全社会固定资产投资',
 'A050504': '制造业全社会固定资产投资',
 'A050505': '电力、燃气及水的生产和供应业全社会固定资产投资',
 'A050506': '建筑业全社会固定资产投资',
 'A050507': '交通运输、仓储和邮政业全社会固定资产投资',
 'A050508': '信息传输计算机服务和软件业全社会固定资产投资',
 'A050509': '批发和零售业全社会固定资产投资',
 'A05050A': '住宿和餐饮业全社会固定资产投资',
 'A05050B': '金融业全社会固定资产投资',
 'A05050C': '房地产业全社会固定资产投资',
 'A05050D': '租赁和商务服务业全社会固定资产投资',
 'A05050E': '科学研究、技术服务和地质勘查业全社会固定资产投资',
 'A05050F': '水利、环境和公共设施管理业全社会固定资产投资',
 'A05050G': '居民服务和其他服务业全社会固定资产投资',
 'A05050H': '教育全社会固定资产投资',
 'A05050I': '卫生、社会保障和社会福利业全社会固定资产投资',
 'A05050J': '文化、体育和娱乐业全社会固定资产投资',
 'A05050K': '公共管理和社会组织全社会固定资产投资',
 'A05050L': '国际组织全社会固定资产投资',
 'A050601': '全社会建设总规模',
 'A050602': '全社会在建总规模',
 'A050603': '全社会在建净规模',
 'A050701': '房屋施工面积',
 'A050702': '住宅房屋施工面积',
 'A050703': '商品住宅房屋施工面积',
 'A050704': '房屋竣工面积',
 'A050705': '住宅房屋竣工面积',
 'A050706': '商品住宅房屋竣工面积',
 'A050707': '房屋竣工价值',
 'A050708': '住宅房屋竣工价值',
 'A050709': '商品住宅房屋竣工价值',
 'A050801': '固定资产投资(不含农户)国家预算内资金',
 'A050802': '固定资产投资(不含农户)国内贷款',
 'A050803': '固定资产投资(不含农户)利用外资',
 'A050804': '固定资产投资(不含农户)自筹资金',
 'A050805': '固定资产投资(不含农户)其他资金',
 'A050901': '固定资产投资(不含农户)中央项目',
 'A050902': '固定资产投资(不含农户)地方项目',
 'A050A01': '固定资产投资(不含农户)',
 'A050A02': '固定资产投资(不含农户)建筑安装工程',
 'A050A03': '固定资产投资(不含农户)设备、工器具购置',
 'A050A04': '固定资产投资(不含农户)其他费用',
 'A050A05': '新建固定资产投资(不含农户)',
 'A050A06': '扩建固定资产投资(不含农户)',
 'A050A07': '改建固定资产投资(不含农户)',
 'A050B01': '固定资产投资(不含农户)建设总规模',
 'A050B02': '固定资产投资(不含农户)在建总规模',
 'A050B03': '固定资产投资(不含农户)在建净规模',
 'A050C01': '固定资产投资(不含农户)',
 'A050C02': '农、林、牧、渔业固定资产投资(不含农户)',
 'A050C03': '采矿业固定资产投资(不含农户)',
 'A050C04': '制造业固定资产投资(不含农户)',
 'A050C05': '电力、燃气及水的生产和供应业固定资产投资(不含农户)',
 'A050C06': '建筑业固定资产投资(不含农户)',
 'A050C07': '交通运输仓储和邮政业固定资产投资(不含农户)',
 'A050C08': '信息传输、计算机服务和软件业固定资产投资(不含农户)',
 'A050C09': '批发和零售业固定资产投资(不含农户)',
 'A050C0A': '住宿和餐饮业固定资产投资(不含农户)',
 'A050C0B': '金融业固定资产投资(不含农户)',
 'A050C0C': '房地产业固定资产投资(不含农户)',
 'A050C0D': '租赁和商务服务业固定资产投资(不含农户)',
 'A050C0E': '科学研究、技术服务和地质勘查业固定资产投资(不含农户)',
 'A050C0F': '水利、环境和公共设施管理业固定资产投资(不含农户)',
 'A050C0G': '居民服务和其他服务业固定资产投资(不含农户)',
 'A050C0H': '教育固定资产投资(不含农户)',
 'A050C0I': '卫生、社会保障和社会福利业固定资产投资(不含农户)',
 'A050C0J': '文化、体育和娱乐业固定资产投资(不含农户)',
 'A050C0K': '公共管理和社会组织固定资产投资(不含农户)',
 'A050C0L': '国际组织固定资产投资(不含农户)',
 'A050D01': '500万元以下固定资产投资(不含农户)',
 'A050D02': '500万元-1亿元固定资产投资(不含农户)',
 'A050D03': '1-5亿元固定资产投资(不含农户)',
 'A050D04': '5-10亿元固定资产投资(不含农户)',
 'A050D05': '10亿元以上固定资产投资(不含农户)',
 'A050E01': '能源工业固定资产投资(不含农户)',
 'A050E02': '煤炭开采及洗选业固定资产投资(不含农户)',
 'A050E03': '石油及天然气开采业固定资产投资(不含农户)',
 'A050E04': '石油及炼焦加工业固定资产投资(不含农户)',
 'A050E05': '电力、热力及燃气的生产和供应业固定资产投资(不含农户)',
 'A050F01': '固定资产投资(不含农户)房屋施工面积',
 'A050F02': '固定资产投资(不含农户)住宅施工面积',
 'A050F03': '固定资产投资(不含农户)房屋竣工面积',
 'A050F04': '固定资产投资(不含农户)住宅竣工面积',
 'A050F05': '固定资产投资(不含农户)竣工房屋价值',
 'A050F06': '固定资产投资(不含农户)竣工住宅价值',
 'A050G01': '新增固定资产投资(不含农户)',
 'A050G02': '农、林、牧、渔业新增固定资产投资(不含农户)',
 'A050G03': '采掘业新增固定资产投资(不含农户)',
 'A050G04': '制造业新增固定资产投资(不含农户)',
 'A050G05': '电力、煤气及水的生产和供应业新增固定资产投资(不含农户)',
 'A050G06': '建筑业新增固定资产投资(不含农户)',
 'A050G07': '交通运输仓储和邮政业新增固定资产投资(不含农户)',
 'A050G08': '信息传输、计算机服务和软件业新增固定资产投资(不含农户)',
 'A050G09': '批发和零售业新增固定资产投资(不含农户)',
 'A050G0A': '住宿和餐饮业新增固定资产投资(不含农户)',
 'A050G0B': '金融业新增固定资产投资(不含农户)',
 'A050G0C': '房地产业新增固定资产投资(不含农户)',
 'A050G0D': '租赁和商务服务业新增固定资产投资(不含农户)',
 'A050G0E': '科学研究、技术服务和地质勘查业新增固定资产投资(不含农户)',
 'A050G0F': '水利、环境和公共设施管理业新增固定资产投资(不含农户)',
 'A050G0G': '居民服务和其他服务业新增固定资产投资(不含农户)',
 'A050G0H': '教育新增固定资产投资(不含农户)',
 'A050G0I': '卫生、社会保障和社会福利业新增固定资产投资(不含农户)',
 'A050G0J': '文化、体育和娱乐业新增固定资产投资(不含农户)',
 'A050G0K': '公共管理和社会组织新增固定资产投资(不含农户)',
 'A050G0L': '国际组织新增固定资产投资(不含农户)',
 'A050H01': '固定资产投资(不含农户)施工项目个数',
 'A050H02': '固定资产投资(不含农户)新开工项目个数',
 'A050H03': '固定资产投资(不含农户)全部建成投产项目个数',
 'A050H04': '固定资产投资(不含农户)项目建成投产率',
 'A050I01': '固定资产投资(不含农户)',
 'A050I02': '固定资产投资(不含农户)新增固定资产',
 'A050I03': '固定资产投资(不含农户)交付使用率',
 'A050J01': '农村农户固定资产投资额',
 'A050J02': '农村农户竣工房屋投资额',
 'A050J03': '农村农户竣工住宅投资额',
 'A050J04': '农村农户施工房屋建筑面积',
 'A050J05': '农村农户竣工房屋建筑面积',
 'A050J06': '农村农户竣工住宅建筑面积',
 'A050J07': '农村农户竣工房屋造价',
 'A050J08': '农村农户竣工住宅造价',
 'A051C01': '房地产开发企业个数',
 'A051C02': '内资房地产开发企业个数',
 'A051C03': '国有房地产开发企业个数',
 'A051C04': '集体房地产开发企业个数',
 'A051C05': '港、澳、台投资房地产开发企业个数',
 'A051C06': '外商投资房地产开发企业个数',
 'A051D01': '房地产开发企业平均从业人数',
 'A051D02': '内资房地产开发企业平均从业人数',
 'A051D03': '国有房地产开发企业平均从业人数',
 'A051D04': '集体房地产开发企业平均从业人数',
 'A051D05': '港、澳、台投资房地产开发企业平均从业人数',
 'A051D06': '外商投资房地产开发企业平均从业人数',
 'A051E01': '房地产开发企业待开发土地面积',
 'A051E02': '房地产开发企业购置土地面积',
 'A051E03': '房地产开发企业土地成交价款',
 'A051E04': '房地产开发企业土地购置费用',
 'A051F01': '房地产开发企业计划总投资',
 'A051F02': '房地产开发企业自开始建设至本年底累计完成投资',
 'A051F03': '房地产开发企业本年完成投资额',
 'A051F04': '房地产开发企业建筑安装工程本年完成投资额',
 'A051F05': '房地产开发企业设备工器具购置本年完成投资额',
 'A051F06': '房地产开发企业其他费用本年完成投资额',
 'A051G01': '房地产开发投资额',
 'A051G02': '房地产开发住宅投资额',
 'A051G03': '房地产开发别墅、高档公寓投资额',
 'A051G04': '房地产开发办公楼投资额',
 'A051G05': '房地产开发商业营业用房投资额',
 'A051G06': '房地产开发其他投资额',
 'A051H01': '房地产开发企业本年实际到位资金',
 'A051H02': '房地产开发企业国内贷款',
 'A051H03': '房地产开发企业利用外资',
 'A051H04': '房地产开发企业外商直接投资',
 'A051H05': '房地产开发企业自筹资金',
 'A051H06': '房地产开发企业其他资金来源',
 'A051H07': '房地产开发企业定金及预收款',
 'A051H08': '房地产开发企业个人按揭贷款',
 'A051H09': '房地产开发企业其他到位资金',
 'A051I01': '房地产开发企业施工房屋面积',
 'A051I02': '房地产开发企业竣工房屋面积',
 'A051I03': '房地产开发企业房屋建筑面积竣工率',
 'A051I04': '房地产开发企业竣工房屋价值',
 'A051I05': '房地产开发企业竣工房屋造价',
 'A051J01': '房地产开发企业新开工房屋面积',
 'A051J02': '房地产开发企业住宅新开工房屋面积',
 'A051J03': '房地产开发企业别墅、高档公寓新开工房屋面积',
 'A051J04': '房地产开发企业办公楼新开工房屋面积',
 'A051J05': '房地产开发企业商业营业用房新开工房屋面积',
 'A051J06': '房地产开发企业其他用途新开工房屋面积',
 'A051K01': '商品房销售面积',
 'A051K02': '住宅商品房销售面积',
 'A051K03': '别墅、高档公寓销售面积',
 'A051K04': '办公楼商品房销售面积',
 'A051K05': '商业营业用房销售面积',
 'A051K06': '其他商品房销售面积',
 'A051L01': '商品房销售额',
 'A051L02': '住宅商品房销售额',
 'A051L03': '别墅、高档公寓销售额',
 'A051L04': '办公楼销售额',
 'A051L05': '商业营业用房销售额',
 'A051L06': '其他商品房销售额',
 'A051M01': '商品房平均销售价格',
 'A051M02': '住宅商品房平均销售价格',
 'A051M03': '别墅、高档公寓平均销售价格',
 'A051M04': '办公楼商品房平均销售价格',
 'A051M05': '商业营业用房平均销售价格',
 'A051M06': '其他商品房平均销售价格',
 'A051N01': '房地产开发企业实收资本',
 'A051N02': '房地产开发企业资产总计',
 'A051N03': '房地产开发企业累计折旧',
 'A051N04': '房地产开发企业本年折旧',
 'A051N05': '房地产开发企业负债合计',
 'A051N06': '房地产开发企业所有者权益',
 'A051N07': '房地产开发企业资产负债率',
 'A051O01': '房地产开发企业主营业务收入',
 'A051O02': '房地产开发企业土地转让收入',
 'A051O03': '房地产开发企业商品房销售收入',
 'A051O04': '房地产开发企业房屋出租收入',
 'A051O05': '房地产开发企业其他收入',
 'A051O06': '房地产开发企业主营业务税金及附加',
 'A051O07': '房地产开发企业营业利润',
 'A051P01': '500万元以下房地产开发投资额',
 'A051P02': '500-1000万元房地产开发投资额',
 'A051P03': '1000-3000万元房地产开发投资额',
 'A051P04': '3000-5000万元房地产开发投资额',
 'A051P05': '5000万-1亿元房地产开发投资额',
 'A051P06': '1-5亿元房地产开发投资额',
 'A051P07': '5-10亿元房地产开发投资额',
 'A051P08': '10亿元以上房地产开发投资额',
 'A051Q01': '房地产开发企业住宅竣工套数',
 'A051Q02': '房地产开发企业别墅、高档公寓竣工套数',
 'A051Q03': '房地产开发企业住宅销售套数',
 'A051Q04': '房地产开发企业别墅、高档公寓销售套数',
 'A060101': '经营单位所在地进出口总额',
 'A060102': '经营单位所在地出口总额',
 'A060103': '经营单位所在地进口总额',
 'A060201': '境内目的地和货源地进出口总额',
 'A060202': '境内目的地和货源地出口总额',
 'A060203': '境内目的地和货源地进口总额',
 'A060301': '外商投资企业进出口总额',
 'A060302': '外商投资企业出口总额',
 'A060303': '外商投资企业进口总额',
 'A060401': '外商投资企业数',
 'A060402': '外商投资企业投资总额',
 'A060403': '外商投资企业注册资本',
 'A060404': '外方外商投资企业注册资本',
 'A070101': '国有经济能源工业固定资产投资',
 'A070102': '国有经济煤炭采选业固定资产投资',
 'A070103': '国有经济石油和天然气开采业固定资产投资',
 'A070104': '国有经济电力、蒸汽、热水生产和供应业固定资产投资',
 'A070105': '国有经济石油加工及炼焦业固定资产投资',
 'A070106': '国有经济煤气生产和供应业固定资产投资',
 'A070201': '能源工业投资',
 'A070202': '煤炭采选业投资',
 'A070203': '石油和天然气开采业投资',
 'A070204': '电力、蒸汽、热水生产和供应业投资',
 'A070205': '石油加工及炼焦业投资',
 'A070206': '煤气生产和供应业投资',
 'A070301': '焦炭生产量',
 'A070302': '原油生产量',
 'A070303': '汽油生产量',
 'A070304': '煤油生产量',
 'A070305': '柴油生产量',
 'A070306': '燃料油生产量',
 'A070307': '天然气生产量',
 'A070308': '发电量',
 'A070309': '水力发电量',
 'A07030A': '火力发电量',
 'A070401': '城市天然气供气总量',
 'A070402': '城市天然气用气人口',
 'A070403': '城市人工煤气供气总量',
 'A070404': '城市人工煤气用气人口',
 'A070405': '城市液化石油气供气总量',
 'A070406': '城市液化石油气用气人口',
 'A070501': '蒸汽供热能力',
 'A070502': '热水供热能力',
 'A070601': '煤炭消费量',
 'A070602': '焦炭消费量',
 'A070603': '原油消费量',
 'A070604': '汽油消费量',
 'A070605': '煤油消费量',
 'A070606': '柴油消费量',
 'A070607': '燃料油消费量',
 'A070608': '天然气消费量',
 'A070609': '电力消费量',
 'A070701': '单位地区生产总值能耗(等价值)',
 'A070702': '单位地区生产总值能耗(等价值)_同比增长',
 'A070703': '单位工业增加值能耗(规模以上当量值)',
 'A070704': '单位工业增加值能耗(规模以上当量值)_同比增长',
 'A070705': '单位地区生产总值电耗(等价值)',
 'A070706': '单位地区生产总值电耗(等价值)_同比增长',
 'A080101': '地方财政一般预算收入',
 'A080102': '地方财政税收收入',
 'A080103': '地方财政国内增值税',
 'A080104': '地方财政营业税',
 'A080105': '地方财政企业所得税',
 'A080106': '地方财政个人所得税',
 'A080107': '地方财政资源税',
 'A080108': '地方财政固定资产投资方向调节税',
 'A080109': '地方财政城市维护建设税',
 'A08010A': '地方财政房产税',
 'A08010B': '地方财政印花税',
 'A08010C': '地方财政城镇土地使用税',
 'A08010D': '地方财政土地增值税',
 'A08010E': '地方财政车船税',
 'A08010F': '地方财政耕地占用税',
 'A08010G': '地方财政契税',
 'A08010H': '地方财政烟叶税',
 'A08010I': '地方财政其他税收收入',
 'A08010J': '地方财政非税收入',
 'A08010K': '地方财政专项收入',
 'A08010L': '地方财政行政事业性收费收入',
 'A08010M': '地方财政罚没收入',
 'A08010N': '地方财政国有资本经营收入',
 'A08010O': '地方财政国有资源(资产)有偿使用收入',
 'A08010P': '地方财政其他非税收入',
 'A080201': '地方财政一般预算支出',
 'A080202': '地方财政一般公共服务支出',
 'A080203': '地方财政外交支出',
 'A080204': '地方财政国防支出',
 'A080205': '地方财政公共安全支出',
 'A080206': '地方财政教育支出',
 'A080207': '地方财政科学技术支出',
 'A080208': '地方财政文化体育与传媒支出',
 'A080209': '地方财政社会保障和就业支出',
 'A08020A': '地方财政医疗卫生支出',
 'A08020B': '地方财政环境保护支出',
 'A08020C': '地方财政城乡社区事务支出',
 'A08020D': '地方财政农林水事务支出',
 'A08020E': '地方财政交通运输支出',
 'A08020F': '地方财政资源勘探电力信息等事务支出',
 'A08020G': '地方财政商业服务业等事务支出',
 'A08020H': '地方财政金融监管支出',
 'A08020I': '地方财政地震灾后重建支出',
 'A08020J': '地方财政国土资源气象等事务支出决策数',
 'A08020K': '地方财政住房保障支出支出',
 'A08020L': '地方财政粮油物资储备管理等事务',
 'A08020M': '地方财政国债还本付息支出',
 'A08020N': '地方财政其他支出',
 'A090101': '居民消费价格指数(上年=100)',
 'A090102': '城市居民消费价格指数(上年=100)',
 'A090103': '农村居民消费价格指数(上年=100)',
 'A090104': '商品零售价格指数(上年=100)',
 'A090105': '城市商品零售价格指数(上年=100)',
 'A090106': '农村商品零售价格指数(上年=100)',
 'A090201': '居民消费价格指数(上年=100)',
 'A090202': '食品类居民消费价格指数(上年=100)',
 'A090203': '粮食类居民消费价格指数(上年=100)',
 'A090204': '油脂类居民消费价格指数(上年=100)',
 'A090205': '肉禽及其制品类居民消费价格指数(上年=100)',
 'A090206': '蛋类居民消费价格指数(上年=100)',
 'A090207': '水产品类居民消费价格指数(上年=100)',
 'A090208': '菜类居民消费价格指数(上年=100)',
 'A090209': '鲜菜类居民消费价格指数(上年=100)',
 'A09020A': '干鲜瓜果类居民消费价格指数(上年=100)',
 'A09020B': '鲜果类居民消费价格指数(上年=100)',
 'A09020C': '在外用膳食品类居民消费价格指数(上年=100)',
 'A09020D': '烟酒及用品类居民消费价格指数(上年=100)',
 'A09020E': '烟草类居民消费价格指数(上年=100)',
 'A09020F': '酒类居民消费价格指数(上年=100)',
 'A09020G': '衣着类居民消费价格指数(上年=100)',
 'A09020H': '服装类居民消费价格指数(上年=100)',
 'A09020I': '衣着材料类居民消费价格指数(上年=100)',
 'A09020J': '鞋袜帽类居民消费价格指数(上年=100)',
 'A09020K': '衣着加工服务费类居民消费价格指数(上年=100)',
 'A09020L': '家庭设备用品及服务类居民消费价格指数(上年=100)',
 'A09020M': '耐用消费品类居民消费价格指数(上年=100)',
 'A09020N': '室内装饰品类居民消费价格指数(上年=100)',
 'A09020O': '床上用品类居民消费价格指数(上年=100)',
 'A09020P': '家庭日用杂品类居民消费价格指数(上年=100)',
 'A09020Q': '家庭服务及加工维修服务费类居民消费价格指数(上年=100)',
 'A09020R': '医疗保健和个人用品类居民消费价格指数(上年=100)',
 'A09020S': '医疗保健类居民消费价格指数(上年=100)',
 'A09020T': '医疗器具及用品类居民消费价格指数(上年=100)',
 'A09020U': '中药材及中成药类居民消费价格指数(上年=100)',
 'A09020V': '西药类居民消费价格指数(上年=100)',
 'A09020W': '保健器具及用品类居民消费价格指数(上年=100)',
 'A09020X': '医疗保健服务类居民消费价格指数(上年=100)',
 'A09020Y': '个人用品及服务类居民消费价格指数(上年=100)',
 'A09020Z': '化妆美容用品类居民消费价格指数(上年=100)',
 'A090210': '卫生用品类居民消费价格指数(上年=100)',
 'A090211': '个人饰品类居民消费价格指数(上年=100)',
 'A090212': '个人服务类居民消费价格指数(上年=100)',
 'A090213': '交通和通信类居民消费价格指数(上年=100)',
 'A090214': '交通类居民消费价格指数(上年=100)',
 'A090215': '交通工具类居民消费价格指数(上年=100)',
 'A090216': '车用燃料及零配件类居民消费价格指数(上年=100)',
 'A090217': '车辆使用及维修费类居民消费价格指数(上年=100)',
 'A090218': '市内公共交通费类居民消费价格指数(上年=100)',
 'A090219': '城市间交通费类居民消费价格指数(上年=100)',
 'A09021A': '通信类居民消费价格指数(上年=100)',
 'A09021B': '通信工具类居民消费价格指数(上年=100)',
 'A09021C': '通信服务类居民消费价格指数(上年=100)',
 'A09021D': '娱乐教育文化类居民消费价格指数(上年=100)',
 'A09021E': '文娱用耐用消费品及服务类居民消费价格指数(上年=100)',
 'A09021F': '教育类居民消费价格指数(上年=100)',
 'A09021G': '教材及参考书类居民消费价格指数(上年=100)',
 'A09021H': '学杂托幼费类居民消费价格指数(上年=100)',
 'A09021I': '文化娱乐类居民消费价格指数(上年=100)',
 'A09021J': '文化娱乐用品类居民消费价格指数(上年=100)',
 'A09021K': '书报杂志类居民消费价格指数(上年=100)',
 'A09021L': '文娱费类居民消费价格指数(上年=100)',
 'A09021M': '旅游类居民消费价格指数(上年=100)',
 'A09021N': '居住类居民消费价格指数(上年=100)',
 'A09021O': '建房及装修材料类居民消费价格指数(上年=100)',
 'A09021P': '租房类居民消费价格指数(上年=100)',
 'A09021Q': '自有住房类居民消费价格指数(上年=100)',
 'A09021R': '水电燃料类居民消费价格指数(上年=100)',
 'A090301': '农村居民消费价格指数(上年=100)',
 'A090302': '食品类农村居民消费价格指数(上年=100)',
 'A090303': '粮食类农村居民消费价格指数(上年=100)',
 'A090304': '淀粉及制品类农村居民消费价格指数(上年=100)',
 'A090305': '干豆类及豆制品类农村居民消费价格指数(上年=100)',
 'A090306': '油脂类农村居民消费价格指数(上年=100)',
 'A090307': '肉禽及其制品类农村居民消费价格指数(上年=100)',
 'A090308': '食用畜肉及副产品类农村居民消费价格指数(上年=100)',
 'A090309': '禽类农村居民消费价格指数(上年=100)',
 'A09030A': '加工肉禽类农村居民消费价格指数(上年=100)',
 'A09030B': '蛋类农村居民消费价格指数(上年=100)',
 'A09030C': '水产品类农村居民消费价格指数(上年=100)',
 'A09030D': '鱼类农村居民消费价格指数(上年=100)',

In [278]:
# 创建地区字典
地区字典 = df_r.set_index("id")['name'].to_dict()
地区字典

{110000: '北京市',
 120000: '天津市',
 130000: '河北省',
 140000: '山西省',
 150000: '内蒙古自治区',
 210000: '辽宁省',
 220000: '吉林省',
 230000: '黑龙江省',
 310000: '上海市',
 320000: '江苏省',
 330000: '浙江省',
 340000: '安徽省',
 350000: '福建省',
 360000: '江西省',
 370000: '山东省',
 410000: '河南省',
 420000: '湖北省',
 430000: '湖南省',
 440000: '广东省',
 450000: '广西壮族自治区',
 460000: '海南省',
 500000: '重庆市',
 510000: '四川省',
 520000: '贵州省',
 530000: '云南省',
 540000: '西藏自治区',
 610000: '陕西省',
 620000: '甘肃省',
 630000: '青海省',
 640000: '宁夏回族自治区',
 650000: '新疆维吾尔自治区'}

In [279]:
df_raw.reset_index()

             zb     reg    sj       data
0       A010101  110000  2018        NaN
1       A010101  110000  2017        NaN
2       A010101  110000  2016        NaN
3       A010101  110000  2015        NaN
4       A010101  110000  2014        NaN
...         ...     ...   ...        ...
908295  A0S0B05  650000  2013  33.856600
908296  A0S0B05  650000  2012  24.914044
908297  A0S0B05  650000  2011        NaN
908298  A0S0B05  650000  2010        NaN
908299  A0S0B05  650000  2009        NaN

[908300 rows x 4 columns]

In [280]:
# 指标字典建立->zb指标
df = df_raw.reset_index().set_index("zb").rename(index=指标字典)
df

                   reg    sj       data
zb
地级区划数           110000  2018        NaN
地级区划数           110000  2017        NaN
地级区划数           110000  2016        NaN
地级区划数           110000  2015        NaN
地级区划数           110000  2014        NaN
...                ...   ...        ...
城乡居民社会养老保险累计结余  650000  2013  33.856600
城乡居民社会养老保险累计结余  650000  2012  24.914044
城乡居民社会养老保险累计结余  650000  2011        NaN
城乡居民社会养老保险累计结余  650000  2010        NaN
城乡居民社会养老保险累计结余  650000  2009        NaN

[908300 rows x 3 columns]

In [281]:
# 
# reg->地区
df = df.reset_index().set_index("reg").rename(index=地区字典)
df

                      zb    sj       data
reg
北京市                地级区划数  2018        NaN
北京市                地级区划数  2017        NaN
北京市                地级区划数  2016        NaN
北京市                地级区划数  2015        NaN
北京市                地级区划数  2014        NaN
...                  ...   ...        ...
新疆维吾尔自治区  城乡居民社会养老保险累计结余  2013  33.856600
新疆维吾尔自治区  城乡居民社会养老保险累计结余  2012  24.914044
新疆维吾尔自治区  城乡居民社会养老保险累计结余  2011        NaN
新疆维吾尔自治区  城乡居民社会养老保险累计结余  2010        NaN
新疆维吾尔自治区  城乡居民社会养老保险累计结余  2009        NaN

[908300 rows x 3 columns]

In [282]:
# 地区字典重命名
df_zh = df.reset_index().rename(columns={"reg":"地区","zb":"指标",\
                                         "sj":"年","data":"数据",})
df_zh

              地区              指标     年         数据
0            北京市           地级区划数  2018        NaN
1            北京市           地级区划数  2017        NaN
2            北京市           地级区划数  2016        NaN
3            北京市           地级区划数  2015        NaN
4            北京市           地级区划数  2014        NaN
...          ...             ...   ...        ...
908295  新疆维吾尔自治区  城乡居民社会养老保险累计结余  2013  33.856600
908296  新疆维吾尔自治区  城乡居民社会养老保险累计结余  2012  24.914044
908297  新疆维吾尔自治区  城乡居民社会养老保险累计结余  2011        NaN
908298  新疆维吾尔自治区  城乡居民社会养老保险累计结余  2010        NaN
908299  新疆维吾尔自治区  城乡居民社会养老保险累计结余  2009        NaN

[908300 rows x 4 columns]

# 数据切片

In [283]:
# 切数据
dslice = df_zh [ df_zh.指标.str.contains("城镇单位就业人员") ]
dslice

             地区                     指标     年          数据
19530       北京市               城镇单位就业人员  2018         NaN
19531       北京市               城镇单位就业人员  2017    812.8589
19532       北京市               城镇单位就业人员  2016    791.5197
19533       北京市               城镇单位就业人员  2015    777.3448
19534       北京市               城镇单位就业人员  2014    755.8601
...         ...                    ...   ...         ...
56725  新疆维吾尔自治区  公共管理和社会组织城镇单位就业人员平均工资  2013  46636.0000
56726  新疆维吾尔自治区  公共管理和社会组织城镇单位就业人员平均工资  2012  45071.0000
56727  新疆维吾尔自治区  公共管理和社会组织城镇单位就业人员平均工资  2011  39862.0000
56728  新疆维吾尔自治区  公共管理和社会组织城镇单位就业人员平均工资  2010  35950.0000
56729  新疆维吾尔自治区  公共管理和社会组织城镇单位就业人员平均工资  2009  31217.0000

[22940 rows x 4 columns]

In [284]:
# 查看
指标分的可能性 = dslice.指标.unique()
指标分的可能性

array(['城镇单位就业人员', '农林牧渔业城镇单位就业人员', '采矿业城镇单位就业人员', '制造业城镇单位就业人员',
       '电力、燃气及水的生产和供应业城镇单位就业人员', '建筑业城镇单位就业人员', '交通运输、仓储及邮电通信业城镇单位就业人员',
       '信息传输、计算机服务和软件业城镇单位就业人员', '批发和零售业城镇单位就业人员', '住宿和餐饮业城镇单位就业人员',
       '金融业城镇单位就业人员', '房地产业城镇单位就业人员', '租赁和商务服务业城镇单位就业人员',
       '科学研究、技术服务和地质勘查业城镇单位就业人员', '水利、环境和公共设施管理业城镇单位就业人员',
       '居民服务和其他服务业城镇单位就业人员', '教育业城镇单位就业人员', '卫生、社会保障和社会福利业城镇单位就业人员',
       '文化、体育和娱乐业城镇单位就业人员', '公共管理和社会组织城镇单位就业人员', '城镇单位就业人员工资总额',
       '国有城镇单位就业人员工资总额', '其他城镇单位就业人员工资总额', '城镇单位就业人员工资总额指数(上年=100)',
       '国有城镇单位就业人员工资总额指数(上年=100)', '其他城镇单位就业人员工资总额指数(上年=100)',
       '城镇单位就业人员平均工资', '城镇单位就业人员平均货币工资指数(上年=100)',
       '国有城镇单位就业人员平均货币工资指数(上年=100)', '其他城镇单位就业人员平均货币工资指数(上年=100)',
       '城镇单位就业人员平均实际工资指数(上年=100)', '国有城镇单位就业人员平均实际工资指数(上年=100)',
       '其他城镇单位就业人员平均实际工资指数(上年=100)', '农、林、牧、渔业城镇单位就业人员工资总额',
       '采矿业城镇单位就业人员工资总额', '制造业城镇单位就业人员工资总额', '电力、燃气及水的生产和供应业城镇单位就业人员工资总额',
       '建筑业城镇单位就业人员工资总额', '交通运输、仓储和邮政业城镇单位就业人员工资总额',
       '信息传输、计算机服务和软件业城镇单位就业人员工资总额', '批发和零售业城镇单位就业人员工资总额',
       '住宿和餐饮业城镇单位就业人员工资总额', '金融业城镇单位就业人员工资总额', '房地产业城镇单位就业人员工资总额',
       '租赁和商务服务业城镇单位就业人员工资总额', '科学研究、技术服务和地质勘查业城镇单位就业人员工资总额',
       '水利、环境和公共设施管理业城镇单位就业人员工资总额', '居民服务和其他服务业城镇单位就业人员工资总额',
       '教育城镇单位就业人员工资总额', '卫生、社会保障和社会福利业城镇单位就业人员工资总额',
       '文化、体育和娱乐业城镇单位就业人员工资总额', '公共管理和社会组织城镇单位就业人员工资总额',
       '农、林、牧、渔业城镇单位就业人员平均工资', '采矿业城镇单位就业人员平均工资', '制造业城镇单位就业人员平均工资',
       '电力、燃气及水的生产和供应业城镇单位就业人员平均工资', '建筑业城镇单位就业人员平均工资',
       '交通运输、仓储和邮政业城镇单位就业人员平均工资', '信息传输、计算机服务和软件业城镇单位就业人员平均工资',
       '批发和零售业城镇单位就业人员平均工资', '住宿和餐饮业城镇单位就业人员平均工资', '金融业城镇单位就业人员平均工资',
       '房地产业城镇单位就业人员平均工资', '租赁和商务服务业城镇单位就业人员平均工资',
       '科学研究、技术服务和地质勘查业城镇单位就业人员平均工资', '水利、环境和公共设施管理业城镇单位就业人员平均工资',
       '居民服务和其他服务业城镇单位就业人员平均工资', '教育城镇单位就业人员平均工资',
       '卫生、社会保障和社会福利业城镇单位就业人员平均工资', '文化、体育和娱乐业城镇单位就业人员平均工资',
       '公共管理和社会组织城镇单位就业人员平均工资'], dtype=object)

In [285]:
# 分的可能性
指标分的可能性 = [ x.split("城镇单位就业") for x in dslice.指标.unique() ]
指标分的可能性

[['', '人员'],
 ['农林牧渔业', '人员'],
 ['采矿业', '人员'],
 ['制造业', '人员'],
 ['电力、燃气及水的生产和供应业', '人员'],
 ['建筑业', '人员'],
 ['交通运输、仓储及邮电通信业', '人员'],
 ['信息传输、计算机服务和软件业', '人员'],
 ['批发和零售业', '人员'],
 ['住宿和餐饮业', '人员'],
 ['金融业', '人员'],
 ['房地产业', '人员'],
 ['租赁和商务服务业', '人员'],
 ['科学研究、技术服务和地质勘查业', '人员'],
 ['水利、环境和公共设施管理业', '人员'],
 ['居民服务和其他服务业', '人员'],
 ['教育业', '人员'],
 ['卫生、社会保障和社会福利业', '人员'],
 ['文化、体育和娱乐业', '人员'],
 ['公共管理和社会组织', '人员'],
 ['', '人员工资总额'],
 ['国有', '人员工资总额'],
 ['其他', '人员工资总额'],
 ['', '人员工资总额指数(上年=100)'],
 ['国有', '人员工资总额指数(上年=100)'],
 ['其他', '人员工资总额指数(上年=100)'],
 ['', '人员平均工资'],
 ['', '人员平均货币工资指数(上年=100)'],
 ['国有', '人员平均货币工资指数(上年=100)'],
 ['其他', '人员平均货币工资指数(上年=100)'],
 ['', '人员平均实际工资指数(上年=100)'],
 ['国有', '人员平均实际工资指数(上年=100)'],
 ['其他', '人员平均实际工资指数(上年=100)'],
 ['农、林、牧、渔业', '人员工资总额'],
 ['采矿业', '人员工资总额'],
 ['制造业', '人员工资总额'],
 ['电力、燃气及水的生产和供应业', '人员工资总额'],
 ['建筑业', '人员工资总额'],
 ['交通运输、仓储和邮政业', '人员工资总额'],
 ['信息传输、计算机服务和软件业', '人员工资总额'],
 ['批发和零售业', '人员工资总额'],
 ['住宿和餐饮业', '人员工资总额'],
 ['金融业', '人员工资总额'],
 ['房地产业', '人员工资总额'],
 ['租赁和商务服务业', '人员工资总额'],
 ['科学研究、技术服务和地质勘查业', '人员工资总额'],
 ['水利、环境和公共设施管理业', '人员工资总额'],
 ['居民服务和其他服务业', '人员工资总额'],
 ['教育', '人员工资总额'],
 ['卫生、社会保障和社会福利业', '人员工资总额'],
 ['文化、体育和娱乐业', '人员工资总额'],
 ['公共管理和社会组织', '人员工资总额'],
 ['农、林、牧、渔业', '人员平均工资'],
 ['采矿业', '人员平均工资'],
 ['制造业', '人员平均工资'],
 ['电力、燃气及水的生产和供应业', '人员平均工资'],
 ['建筑业', '人员平均工资'],
 ['交通运输、仓储和邮政业', '人员平均工资'],
 ['信息传输、计算机服务和软件业', '人员平均工资'],
 ['批发和零售业', '人员平均工资'],
 ['住宿和餐饮业', '人员平均工资'],
 ['金融业', '人员平均工资'],
 ['房地产业', '人员平均工资'],
 ['租赁和商务服务业', '人员平均工资'],
 ['科学研究、技术服务和地质勘查业', '人员平均工资'],
 ['水利、环境和公共设施管理业', '人员平均工资'],
 ['居民服务和其他服务业', '人员平均工资'],
 ['教育', '人员平均工资'],
 ['卫生、社会保障和社会福利业', '人员平均工资'],
 ['文化、体育和娱乐业', '人员平均工资'],
 ['公共管理和社会组织', '人员平均工资']]

In [286]:
# 取值
指标分的可能性_取 = [ [x,y] for (x,y) in 指标分的可能性 if (y=='人员平均工资' or y=='人员') and x !='' ]
指标分的可能性_取

[['农林牧渔业', '人员'],
 ['采矿业', '人员'],
 ['制造业', '人员'],
 ['电力、燃气及水的生产和供应业', '人员'],
 ['建筑业', '人员'],
 ['交通运输、仓储及邮电通信业', '人员'],
 ['信息传输、计算机服务和软件业', '人员'],
 ['批发和零售业', '人员'],
 ['住宿和餐饮业', '人员'],
 ['金融业', '人员'],
 ['房地产业', '人员'],
 ['租赁和商务服务业', '人员'],
 ['科学研究、技术服务和地质勘查业', '人员'],
 ['水利、环境和公共设施管理业', '人员'],
 ['居民服务和其他服务业', '人员'],
 ['教育业', '人员'],
 ['卫生、社会保障和社会福利业', '人员'],
 ['文化、体育和娱乐业', '人员'],
 ['公共管理和社会组织', '人员'],
 ['农、林、牧、渔业', '人员平均工资'],
 ['采矿业', '人员平均工资'],
 ['制造业', '人员平均工资'],
 ['电力、燃气及水的生产和供应业', '人员平均工资'],
 ['建筑业', '人员平均工资'],
 ['交通运输、仓储和邮政业', '人员平均工资'],
 ['信息传输、计算机服务和软件业', '人员平均工资'],
 ['批发和零售业', '人员平均工资'],
 ['住宿和餐饮业', '人员平均工资'],
 ['金融业', '人员平均工资'],
 ['房地产业', '人员平均工资'],
 ['租赁和商务服务业', '人员平均工资'],
 ['科学研究、技术服务和地质勘查业', '人员平均工资'],
 ['水利、环境和公共设施管理业', '人员平均工资'],
 ['居民服务和其他服务业', '人员平均工资'],
 ['教育', '人员平均工资'],
 ['卫生、社会保障和社会福利业', '人员平均工资'],
 ['文化、体育和娱乐业', '人员平均工资'],
 ['公共管理和社会组织', '人员平均工资']]

In [287]:
# 进一步切片
指标分的可能性_取_all = ["城镇单位就业".join(x) for x in 指标分的可能性_取]
指标分的可能性_取_all

['农林牧渔业城镇单位就业人员',
 '采矿业城镇单位就业人员',
 '制造业城镇单位就业人员',
 '电力、燃气及水的生产和供应业城镇单位就业人员',
 '建筑业城镇单位就业人员',
 '交通运输、仓储及邮电通信业城镇单位就业人员',
 '信息传输、计算机服务和软件业城镇单位就业人员',
 '批发和零售业城镇单位就业人员',
 '住宿和餐饮业城镇单位就业人员',
 '金融业城镇单位就业人员',
 '房地产业城镇单位就业人员',
 '租赁和商务服务业城镇单位就业人员',
 '科学研究、技术服务和地质勘查业城镇单位就业人员',
 '水利、环境和公共设施管理业城镇单位就业人员',
 '居民服务和其他服务业城镇单位就业人员',
 '教育业城镇单位就业人员',
 '卫生、社会保障和社会福利业城镇单位就业人员',
 '文化、体育和娱乐业城镇单位就业人员',
 '公共管理和社会组织城镇单位就业人员',
 '农、林、牧、渔业城镇单位就业人员平均工资',
 '采矿业城镇单位就业人员平均工资',
 '制造业城镇单位就业人员平均工资',
 '电力、燃气及水的生产和供应业城镇单位就业人员平均工资',
 '建筑业城镇单位就业人员平均工资',
 '交通运输、仓储和邮政业城镇单位就业人员平均工资',
 '信息传输、计算机服务和软件业城镇单位就业人员平均工资',
 '批发和零售业城镇单位就业人员平均工资',
 '住宿和餐饮业城镇单位就业人员平均工资',
 '金融业城镇单位就业人员平均工资',
 '房地产业城镇单位就业人员平均工资',
 '租赁和商务服务业城镇单位就业人员平均工资',
 '科学研究、技术服务和地质勘查业城镇单位就业人员平均工资',
 '水利、环境和公共设施管理业城镇单位就业人员平均工资',
 '居民服务和其他服务业城镇单位就业人员平均工资',
 '教育城镇单位就业人员平均工资',
 '卫生、社会保障和社会福利业城镇单位就业人员平均工资',
 '文化、体育和娱乐业城镇单位就业人员平均工资',
 '公共管理和社会组织城镇单位就业人员平均工资']

In [288]:
df_就业切片 = df_zh.set_index("指标").loc[指标分的可能性_取_all].reset_index()
df_就业切片

                          指标        地区     年          数据
0              农林牧渔业城镇单位就业人员       北京市  2018         NaN
1              农林牧渔业城镇单位就业人员       北京市  2017      3.4116
2              农林牧渔业城镇单位就业人员       北京市  2016      3.6867
3              农林牧渔业城镇单位就业人员       北京市  2015      3.8949
4              农林牧渔业城镇单位就业人员       北京市  2014      3.2331
...                      ...       ...   ...         ...
11775  公共管理和社会组织城镇单位就业人员平均工资  新疆维吾尔自治区  2013  46636.0000
11776  公共管理和社会组织城镇单位就业人员平均工资  新疆维吾尔自治区  2012  45071.0000
11777  公共管理和社会组织城镇单位就业人员平均工资  新疆维吾尔自治区  2011  39862.0000
11778  公共管理和社会组织城镇单位就业人员平均工资  新疆维吾尔自治区  2010  35950.0000
11779  公共管理和社会组织城镇单位就业人员平均工资  新疆维吾尔自治区  2009  31217.0000

[11780 rows x 4 columns]

In [289]:
df_就业切片.describe(include="all")

                      指标     地区             年             数据
count              11780  11780  11780.000000   10591.000000
unique                38     31           NaN            NaN
top     房地产业城镇单位就业人员平均工资    河北省           NaN            NaN
freq                 310    380           NaN            NaN
mean                 NaN    NaN   2013.500000   25995.610415
std                  NaN    NaN      2.872403   31837.310363
min                  NaN    NaN   2009.000000       0.024900
25%                  NaN    NaN   2011.000000      11.323850
50%                  NaN    NaN   2013.500000   11478.000000
75%                  NaN    NaN   2016.000000   46218.500000
max                  NaN    NaN   2018.000000  253637.000000

# 分组数据

In [290]:
# 分进合击分组数据
df_就业切片.groupby(by='指标').agg({"数据":["min","mean","max"]})

                                     数据
                                    min          mean          max
指标
交通运输、仓储及邮电通信业城镇单位就业人员            0.5997     24.556320      85.3999
交通运输、仓储和邮政业城镇单位就业人员平均工资      25098.0000  56241.240143  116763.0000
住宿和餐饮业城镇单位就业人员                   0.3000      8.331891      39.3419
住宿和餐饮业城镇单位就业人员平均工资           13455.0000  31198.731183   61095.0000
信息传输、计算机服务和软件业城镇单位就业人员           0.2235      9.204604      77.4400
信息传输、计算机服务和软件业城镇单位就业人员平均工资   22186.0000  72507.896057  212063.0000
公共管理和社会组织城镇单位就业人员                7.8169     50.301842     116.1762
公共管理和社会组织城镇单位就业人员平均工资        25275.0000  55019.594982  128855.0000
农、林、牧、渔业城镇单位就业人员平均工资          8832.0000  30661.906810   74975.0000
农林牧渔业城镇单位就业人员                    0.3089     10.091744      93.9292
制造业城镇单位就业人员                      0.6612    145.443355    1020.2491
制造业城镇单位就业人员平均工资              21508.0000  45198.247312  106835.0000
卫生、社会保障和社会福利业城镇单位就业人员            1.3830     24.421601      65.8223
卫生、社会保障和社会福利业城镇单位就业人员平均工资    22302.0000  59073.053763  169191.0000
居民服务和其他服务业城镇单位就业人员               0.0557      2.277055      11.0436
居民服务和其他服务业城镇单位就业人员平均工资       16022.0000  35929.476703   67013.0000
建筑业城镇单位就业人员                      0.5018     72.355329     450.1977
建筑业城镇单位就业人员平均工资              16423.0000  40809.896057   99718.0000
房地产业城镇单位就业人员                     0.0249     10.849628      66.3147
房地产业城镇单位就业人员平均工资             15938.0000  45288.530466  120379.0000
批发和零售业城镇单位就业人员                   0.4833     24.356891     102.7835
批发和零售业城镇单位就业人员平均工资           16073.0000  44120.035842  139627.0000
教育业城镇单位就业人员                      3.9384     53.813387     127.4604
教育城镇单位就业人员平均工资               26175.0000  57414.487455  143215.0000
文化、体育和娱乐业城镇单位就业人员                0.5999      4.581411      19.0189
文化、体育和娱乐业城镇单位就业人员平均工资        22377.0000  54176.698925  150810.0000
水利、环境和公共设施管理业城镇单位就业人员            0.1636      8.022701      18.2523
水利、环境和公共设施管理业城镇单位就业人员平均工资    15831.0000  36995.433692   95341.0000
电力、燃气及水的生产和供应业城镇单位就业人员           0.7362     11.707497      32.1821
电力、燃气及水的生产和供应业城镇单位就业人员平均工资   29419.0000  67744.182796  174252.0000
科学研究、技术服务和地质勘查业城镇单位就业人员          0.6790     11.614666      71.2481
科学研究、技术服务和地质勘查业城镇单位就业人员平均工资  26211.0000  66216.186380  176383.0000
租赁和商务服务业城镇单位就业人员                 0.1000     12.672472      88.2695
租赁和商务服务业城镇单位就业人员平均工资         16691.0000  43966.784946  156621.0000
采矿业城镇单位就业人员                      0.0523     18.220504     103.0136
采矿业城镇单位就业人员平均工资              22732.0000  56747.756272  144454.0000
金融业城镇单位就业人员                      0.7717     17.982375      54.4498
金融业城镇单位就业人员平均工资              30627.0000  86977.516129  253637.0000

In [291]:
# 多层次数据
df_就业切片['行业'] = [x.split("城镇单位就业")[0] for x in df_就业切片.指标]
df_就业切片['行业指标'] = [x.split("城镇单位就业")[1] for x in df_就业切片.指标]
df_就业切片

                          指标        地区     年          数据         行业    行业指标
0              农林牧渔业城镇单位就业人员       北京市  2018         NaN      农林牧渔业      人员
1              农林牧渔业城镇单位就业人员       北京市  2017      3.4116      农林牧渔业      人员
2              农林牧渔业城镇单位就业人员       北京市  2016      3.6867      农林牧渔业      人员
3              农林牧渔业城镇单位就业人员       北京市  2015      3.8949      农林牧渔业      人员
4              农林牧渔业城镇单位就业人员       北京市  2014      3.2331      农林牧渔业      人员
...                      ...       ...   ...         ...        ...     ...
11775  公共管理和社会组织城镇单位就业人员平均工资  新疆维吾尔自治区  2013  46636.0000  公共管理和社会组织  人员平均工资
11776  公共管理和社会组织城镇单位就业人员平均工资  新疆维吾尔自治区  2012  45071.0000  公共管理和社会组织  人员平均工资
11777  公共管理和社会组织城镇单位就业人员平均工资  新疆维吾尔自治区  2011  39862.0000  公共管理和社会组织  人员平均工资
11778  公共管理和社会组织城镇单位就业人员平均工资  新疆维吾尔自治区  2010  35950.0000  公共管理和社会组织  人员平均工资
11779  公共管理和社会组织城镇单位就业人员平均工资  新疆维吾尔自治区  2009  31217.0000  公共管理和社会组织  人员平均工资

[11780 rows x 6 columns]

In [292]:
df_就业切片.groupby(['地区','行业','行业指标']).mean()

                                 年            数据
地区   行业             行业指标
上海市  交通运输、仓储及邮电通信业  人员      2013.5     45.014167
     交通运输、仓储和邮政业    人员平均工资  2013.5  81817.888889
     住宿和餐饮业         人员      2013.5     19.851000
                    人员平均工资  2013.5  45158.777778
     信息传输、计算机服务和软件业 人员      2013.5     17.706767
...                            ...           ...
黑龙江省 租赁和商务服务业       人员平均工资  2013.5  38601.444444
     采矿业            人员      2013.5     36.610556
                    人员平均工资  2013.5  51564.777778
     金融业            人员      2013.5     17.099533
                    人员平均工资  2013.5  55194.888889

[1178 rows x 2 columns]

In [293]:
df_就业切片.groupby(['地区','行业','行业指标']).agg({"数据":["min","mean","max"]})

                                    数据
                                   min          mean          max
地区   行业             行业指标
上海市  交通运输、仓储及邮电通信业  人员         35.6329     45.014167      51.4541
     交通运输、仓储和邮政业    人员平均工资  49847.0000  81817.888889  116763.0000
     住宿和餐饮业         人员         10.8191     19.851000      25.5494
                    人员平均工资  29564.0000  45158.777778   60153.0000
     信息传输、计算机服务和软件业 人员          6.5150     17.706767      30.7312
...                                ...           ...          ...
黑龙江省 租赁和商务服务业       人员平均工资  21157.0000  38601.444444   56493.0000
     采矿业            人员         25.5592     36.610556      43.4887
                    人员平均工资  33417.0000  51564.777778   68926.0000
     金融业            人员         13.4821     17.099533      22.6548
                    人员平均工资  37056.0000  55194.888889   66790.0000

[1178 rows x 3 columns]

In [294]:
# 多层次数据报表输出
df_就业切片
df_就业切片.groupby(['行业','行业指标']).agg({"数据":["min","mean","max"]})

                                数据
                               min          mean          max
行业              行业指标
交通运输、仓储及邮电通信业   人员          0.5997     24.556320      85.3999
交通运输、仓储和邮政业     人员平均工资  25098.0000  56241.240143  116763.0000
住宿和餐饮业          人员          0.3000      8.331891      39.3419
                人员平均工资  13455.0000  31198.731183   61095.0000
信息传输、计算机服务和软件业  人员          0.2235      9.204604      77.4400
                人员平均工资  22186.0000  72507.896057  212063.0000
公共管理和社会组织       人员          7.8169     50.301842     116.1762
                人员平均工资  25275.0000  55019.594982  128855.0000
农、林、牧、渔业        人员平均工资   8832.0000  30661.906810   74975.0000
农林牧渔业           人员          0.3089     10.091744      93.9292
制造业             人员          0.6612    145.443355    1020.2491
                人员平均工资  21508.0000  45198.247312  106835.0000
卫生、社会保障和社会福利业   人员          1.3830     24.421601      65.8223
                人员平均工资  22302.0000  59073.053763  169191.0000
居民服务和其他服务业      人员          0.0557      2.277055      11.0436
                人员平均工资  16022.0000  35929.476703   67013.0000
建筑业             人员          0.5018     72.355329     450.1977
                人员平均工资  16423.0000  40809.896057   99718.0000
房地产业            人员          0.0249     10.849628      66.3147
                人员平均工资  15938.0000  45288.530466  120379.0000
批发和零售业          人员          0.4833     24.356891     102.7835
                人员平均工资  16073.0000  44120.035842  139627.0000
教育              人员平均工资  26175.0000  57414.487455  143215.0000
教育业             人员          3.9384     53.813387     127.4604
文化、体育和娱乐业       人员          0.5999      4.581411      19.0189
                人员平均工资  22377.0000  54176.698925  150810.0000
水利、环境和公共设施管理业   人员          0.1636      8.022701      18.2523
                人员平均工资  15831.0000  36995.433692   95341.0000
电力、燃气及水的生产和供应业  人员          0.7362     11.707497      32.1821
                人员平均工资  29419.0000  67744.182796  174252.0000
科学研究、技术服务和地质勘查业 人员          0.6790     11.614666      71.2481
                人员平均工资  26211.0000  66216.186380  176383.0000
租赁和商务服务业        人员          0.1000     12.672472      88.2695
                人员平均工资  16691.0000  43966.784946  156621.0000
采矿业             人员          0.0523     18.220504     103.0136
                人员平均工资  22732.0000  56747.756272  144454.0000
金融业             人员          0.7717     17.982375      54.4498
                人员平均工资  30627.0000  86977.516129  253637.0000

In [295]:
df_就业切片.groupby(['行业','地区']).agg({"数据":["min","mean","max"]})

                           数据
                          min          mean          max
行业            地区
交通运输、仓储及邮电通信业 上海市     35.6329     45.014167      51.4541
              云南省     13.4000     15.667100      17.8598
              内蒙古自治区  16.2429     19.266189      22.7777
              北京市     50.0662     56.857056      60.2262
              吉林省     14.2939     15.836233      17.1587
...                       ...           ...          ...
金融业           辽宁省     20.1945  35018.544628   85433.0000
              重庆市      9.7491  47509.109067  126739.0000
              陕西省     12.8648  33198.138150   86024.0000
              青海省      1.8156  33716.628211   98911.0000
              黑龙江省    13.4821  27605.994211   66790.0000

[682 rows x 3 columns]

In [296]:
# 分组出报表
统一字词 = {"交通运输、仓储及邮电通信业":"交通运输、仓储和邮政业",\
            "农、林、牧、渔业":"农林牧渔业",\
            "教育":"教育业"}
df_就业切片_new = df_就业切片.set_index("行业").rename(index=统一字词).reset_index()
df_就业切片_new.行业.unique()

array(['农林牧渔业', '采矿业', '制造业', '电力、燃气及水的生产和供应业', '建筑业', '交通运输、仓储和邮政业',
       '信息传输、计算机服务和软件业', '批发和零售业', '住宿和餐饮业', '金融业', '房地产业', '租赁和商务服务业',
       '科学研究、技术服务和地质勘查业', '水利、环境和公共设施管理业', '居民服务和其他服务业', '教育业',
       '卫生、社会保障和社会福利业', '文化、体育和娱乐业', '公共管理和社会组织'], dtype=object)

In [297]:
df_就业切片_new.groupby(["行业","行业指标"]).agg({"数据":["min","max","mean"]})

                                数据
                               min          max          mean
行业              行业指标
交通运输、仓储和邮政业     人员          0.5997      85.3999     24.556320
                人员平均工资  25098.0000  116763.0000  56241.240143
住宿和餐饮业          人员          0.3000      39.3419      8.331891
                人员平均工资  13455.0000   61095.0000  31198.731183
信息传输、计算机服务和软件业  人员          0.2235      77.4400      9.204604
                人员平均工资  22186.0000  212063.0000  72507.896057
公共管理和社会组织       人员          7.8169     116.1762     50.301842
                人员平均工资  25275.0000  128855.0000  55019.594982
农林牧渔业           人员          0.3089      93.9292     10.091744
                人员平均工资   8832.0000   74975.0000  30661.906810
制造业             人员          0.6612    1020.2491    145.443355
                人员平均工资  21508.0000  106835.0000  45198.247312
卫生、社会保障和社会福利业   人员          1.3830      65.8223     24.421601
                人员平均工资  22302.0000  169191.0000  59073.053763
居民服务和其他服务业      人员          0.0557      11.0436      2.277055
                人员平均工资  16022.0000   67013.0000  35929.476703
建筑业             人员          0.5018     450.1977     72.355329
                人员平均工资  16423.0000   99718.0000  40809.896057
房地产业            人员          0.0249      66.3147     10.849628
                人员平均工资  15938.0000  120379.0000  45288.530466
批发和零售业          人员          0.4833     102.7835     24.356891
                人员平均工资  16073.0000  139627.0000  44120.035842
教育业             人员          3.9384     127.4604     53.813387
                人员平均工资  26175.0000  143215.0000  57414.487455
文化、体育和娱乐业       人员          0.5999      19.0189      4.581411
                人员平均工资  22377.0000  150810.0000  54176.698925
水利、环境和公共设施管理业   人员          0.1636      18.2523      8.022701
                人员平均工资  15831.0000   95341.0000  36995.433692
电力、燃气及水的生产和供应业  人员          0.7362      32.1821     11.707497
                人员平均工资  29419.0000  174252.0000  67744.182796
科学研究、技术服务和地质勘查业 人员          0.6790      71.2481     11.614666
                人员平均工资  26211.0000  176383.0000  66216.186380
租赁和商务服务业        人员          0.1000      88.2695     12.672472
                人员平均工资  16691.0000  156621.0000  43966.784946
采矿业             人员          0.0523     103.0136     18.220504
                人员平均工资  22732.0000  144454.0000  56747.756272
金融业             人员          0.7717      54.4498     17.982375
                人员平均工资  30627.0000  253637.0000  86977.516129

In [298]:
人员平均工资 = df_就业切片.query("行业指标=='人员平均工资'")

In [299]:
人员平均工资.groupby(['行业','地区']).agg({"数据":["min","mean","max"]})

                         数据
                        min          mean       max
行业          地区
交通运输、仓储和邮政业 上海市     49847.0  81817.888889  116763.0
            云南省     31714.0  54985.111111   80853.0
            内蒙古自治区  34578.0  55693.333333   74613.0
            北京市     46087.0  71454.222222   97567.0
            吉林省     26539.0  48073.888889   67910.0
...                     ...           ...       ...
金融业         辽宁省     45038.0  70013.222222   85433.0
            重庆市     49871.0  95005.666667  126739.0
            陕西省     46122.0  66379.888889   86024.0
            青海省     37456.0  67431.111111   98911.0
            黑龙江省    37056.0  55194.888889   66790.0

[589 rows x 3 columns]

In [300]:
人员平均工资.groupby(['地区']).agg({"数据":["min","mean","max"]})

               数据
              min          mean       max
地区
上海市       29564.0  95373.456140  247568.0
云南省       14853.0  44699.356725  130774.0
内蒙古自治区    15017.0  47498.690058   85135.0
北京市       25006.0  89086.046784  253637.0
吉林省       13636.0  40642.450292   87154.0
四川省       17748.0  49618.280702  101514.0
天津市       20992.0  73773.017544  151778.0
宁夏回族自治区   15529.0  49129.701754  103768.0
安徽省       13437.0  45770.783626   98235.0
山东省       19568.0  50366.672515   94704.0
山西省       13455.0  40518.602339   80556.0
广东省       14469.0  63142.736842  149936.0
广西壮族自治区   15397.0  43223.590643   96818.0
新疆维吾尔自治区  16022.0  50234.625731  105881.0
江苏省       17904.0  61104.783626  143002.0
江西省       15049.0  42360.959064   84304.0
河北省       11330.0  42770.233918  109196.0
河南省       15718.0  40797.461988  103314.0
浙江省       22456.0  66680.111111  165532.0
海南省       10855.0  47224.847953  124017.0
湖北省       15777.0  45400.081871  101551.0
湖南省       14519.0  43279.467836   99320.0
甘肃省       15163.0  40974.327485   85197.0
福建省       15790.0  52346.286550  109757.0
西藏自治区     13522.0  60094.643275  186085.0
贵州省       16895.0  47309.122807  141959.0
辽宁省        8832.0  45122.994152   91990.0
重庆市       17129.0  52280.444444  126739.0
陕西省       16338.0  46612.181287  130891.0
青海省       16825.0  49264.678363  100823.0
黑龙江省      11079.0  42505.538012   73978.0

In [301]:
人员平均工资.groupby(['行业']).agg({"数据":["min","mean","max"]})

                      数据
                     min          mean       max
行业
交通运输、仓储和邮政业      25098.0  56241.240143  116763.0
住宿和餐饮业           13455.0  31198.731183   61095.0
信息传输、计算机服务和软件业   22186.0  72507.896057  212063.0
公共管理和社会组织        25275.0  55019.594982  128855.0
农、林、牧、渔业          8832.0  30661.906810   74975.0
制造业              21508.0  45198.247312  106835.0
卫生、社会保障和社会福利业    22302.0  59073.053763  169191.0
居民服务和其他服务业       16022.0  35929.476703   67013.0
建筑业              16423.0  40809.896057   99718.0
房地产业             15938.0  45288.530466  120379.0
批发和零售业           16073.0  44120.035842  139627.0
教育               26175.0  57414.487455  143215.0
文化、体育和娱乐业        22377.0  54176.698925  150810.0
水利、环境和公共设施管理业    15831.0  36995.433692   95341.0
电力、燃气及水的生产和供应业   29419.0  67744.182796  174252.0
科学研究、技术服务和地质勘查业  26211.0  66216.186380  176383.0
租赁和商务服务业         16691.0  43966.784946  156621.0
采矿业              22732.0  56747.756272  144454.0
金融业              30627.0  86977.516129  253637.0